name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest  # 必须添加运行环境声明
    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 修复 Gradle 执行权限（关键修复）
      - name: Fix Gradle permissions
        run: chmod +x gradlew

      # 3. 调用可复用工作流
      - name: Run plugin CI
        uses: halo-sigs/reusable-workflows/.github/workflows/plugin-ci.yaml@v3
        with:
          ui-path: "ui"
          node-version: '20.x'